.TH MYCAT 3 "September 2025" "Version 0.4.1" "Library Functions Manual"
.SH NAME
mycat \- display the contents of a file
.SH SYNOPSIS
.B #include "myfilefunctions.h"
.br
.B void mycat(const char *filename);
.SH DESCRIPTION
The
.B mycat
function opens the file specified by
.I filename
and prints its contents to standard output.
.SH AUTHOR
Rida Batool <ridabatoolgujjar@gmail.com>

