.TH MYSTRLEN 3 "September 2025" "Version 0.4.1" "Library Functions Manual"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B size_t mystrlen(const char *str);
.SH DESCRIPTION
The
.B mystrlen
function computes the number of characters in the string pointed to by
.I str,
excluding the terminating null byte ('\0').
.SH AUTHOR
Rida Batool <ridabatoolgujjar@gmail.com>

